### ISSUE TITLE
Milestone for gtk-notepad v0.2

### ISSUE THREAD

**Issue by JadedTuna** [Vik2015/gtk-notepad#1]
- [ ] Add search && replace support
- [ ] Add ability to set tab size and use spaces instead of tabs
- [ ] Clean up the code
- [x] Move to GTK 3 [IMPORTANT]
